"""One-column reading copy of the manuscript: PLOS/BSCAN_onecolumn.tex and .pdf.

PLOS/BSCAN_PLOS_ONE.tex stays the only manuscript source and is what gets submitted.  This script derives a copy
for reading: 11 pt on A4 in one column with 2.5 cm margins, justified text, 1.15 line spacing, no line numbers,
the figures shown in place and coloured links.  Every table and figure is placed exactly where it stands in the
source ([H] of the float package).  A table that is too wide for the portrait page (an overfull box in a first
compile) is set on a landscape page (pdflscape), so it is read sideways instead of being shrunk.  Text, tables,
figures, references and placeholders are those of the PLOS file; only the page layout differs.

    python .scripts/build_onecolumn.py      (also run by .scripts/build_all.py after the PLOS manuscript)
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = ROOT / "PLOS"
SOURCE = MANUSCRIPT / "BSCAN_PLOS_ONE.tex"
STEM = "BSCAN_onecolumn"

# (pattern in the PLOS preamble, replacement); every pattern must occur exactly once, so a changed template
# fails loudly instead of giving a silently different layout
LAYOUT = [
    (r"^\\documentclass\[10pt,letterpaper\]\{article\}$", r"\\documentclass[11pt,a4paper]{article}"),
    (r"^\\usepackage\[top=0\.85in,left=2\.75in,footskip=0\.75in\]\{geometry\}$",
     r"\\usepackage[a4paper,margin=2.5cm,footskip=1cm]{geometry}"),
    (r"^\\doublespacing$", r"\\setstretch{1.15}"),
    (r"^\\raggedright\n", ""),
    (r"^\\textwidth 5\.25in\n", ""),
    (r"^\\textheight 8\.75in\n", ""),
    (r"^\\renewcommand\{\\footrule\}\{\\hrule height 2pt \\vspace\{2mm\}\}\n", ""),
    (r"^\\fancyheadoffset\[L\]\{2\.25in\}\n", ""),
    (r"^\\fancyfootoffset\[L\]\{2\.25in\}\n", ""),
    (r"^\\draftfiguresfalse$", r"\\draftfigurestrue"),
]
EXTRA = r"""
% one-column reading copy: no line numbers; tables single-spaced at the 9 pt of the PLOS tables (\small at 10 pt);
% every table and figure exactly where it stands in the source; wide tables on landscape pages; justified
% captions; coloured links
\usepackage{float}
\usepackage{pdflscape}
\renewcommand{\linenumbers}{}
\renewcommand{\tablesetup}{\setstretch{1}\footnotesize}
\makeatletter
\renewenvironment{table}[1][]{\@float{table}[H]}{\end@float}
\renewenvironment{figure}[1][]{\@float{figure}[H]}{\end@float}
\makeatother
\captionsetup{justification=justified}
\hypersetup{colorlinks=true,linkcolor=blue!50!black,citecolor=blue!50!black,urlcolor=blue!60!black}
% no figure taller than 62% of the page (aspect ratio kept), so a tall figure and its caption fit one page
\setkeys{Gin}{height=0.62\textheight,keepaspectratio}

"""
HEADER = """% GENERATED by .scripts/build_onecolumn.py from BSCAN_PLOS_ONE.tex; do not edit (edit the PLOS file).
% One-column reading copy: the body is that of the PLOS manuscript; only the page layout differs.  The
% \\typeout markers around the tables let the script find, in the LaTeX log, the tables that are too wide for
% a portrait page; those are wrapped in a landscape environment.
"""
# a table of the body: a generated table (\input) or a hand-written table environment
BLOCK = re.compile(r"^(?:\\input\{generated/tables/(?P<name>[^}]+)\}|\\begin\{table\}.*?^\\end\{table\})[ \t]*$",
                   re.M | re.S)


def block_key(m: re.Match) -> str:
    if m.group("name"):
        return m.group("name")
    label = re.search(r"\\label\{([^}]*)\}", m.group(0))
    return label.group(1) if label else f"table-at-{m.start()}"


def render(pre: str, body: str, wide: set[str]) -> str:
    """The .tex: layout preamble + body with every table wrapped in log markers (and in landscape when wide)."""
    out, pos = [HEADER, pre, EXTRA], 0
    for m in BLOCK.finditer(body):
        key = block_key(m)
        block = f"\\typeout{{ONECOL-BEGIN {key}}}\n{m.group(0)}\n\\typeout{{ONECOL-END {key}}}"
        if key in wide:
            block = f"\\begin{{landscape}}\n{block}\n\\end{{landscape}}"
        out += [body[pos:m.start()], block]
        pos = m.end()
    out.append(body[pos:])
    return "".join(out)


def too_wide(log: str) -> set[str]:
    """Tables whose block produced an overfull horizontal box (wider than the page allows)."""
    wide, cur = set(), None
    for line in log.splitlines():
        if "ONECOL-BEGIN " in line:
            cur = line.split("ONECOL-BEGIN ", 1)[1].strip()
        elif "ONECOL-END " in line:
            cur = None
        elif cur and line.startswith("Overfull \\hbox"):
            wide.add(cur)
    return wide


def main() -> int:
    if not SOURCE.exists():
        print(f"{SOURCE.relative_to(ROOT)} not found: one-column copy skipped")
        return 1
    src = SOURCE.read_text()
    cut = src.index("\\begin{document}")
    pre, body = src[:cut], src[cut:]
    for pat, rep in LAYOUT:
        pre, n = re.subn(pat, rep, pre, flags=re.M)
        if n != 1:
            raise SystemExit(f"build_onecolumn: expected one match of {pat!r} in the PLOS preamble, found {n}")
    spec = importlib.util.spec_from_file_location("build_all", ROOT / ".scripts" / "build_all.py")
    build_all = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build_all)
    tex, log = MANUSCRIPT / f"{STEM}.tex", MANUSCRIPT / f"{STEM}.log"
    pdflatex = build_all.tex_tool("pdflatex")
    wide: set[str] = set()
    if pdflatex:  # pass 1 (draft, one run): which tables overflow a portrait page?
        tex.write_text(render(pre, body, wide))
        subprocess.run([pdflatex, "-interaction=nonstopmode", "-draftmode", STEM], cwd=MANUSCRIPT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        wide = too_wide(log.read_text(errors="replace"))
    tex.write_text(render(pre, body, wide))
    print(f"wrote {tex.relative_to(ROOT)}; landscape tables: {', '.join(sorted(wide)) or 'none'}")
    if not pdflatex:
        print("pdflatex not found (set TEXBIN or add it to PATH): one-column copy not compiled")
        return 0
    build_all.latex(STEM)
    more = too_wide(log.read_text(errors="replace")) - wide  # a cross-reference that got wider, for example
    if more:
        wide |= more
        tex.write_text(render(pre, body, wide))
        print(f"also landscape after the full build: {', '.join(sorted(more))}")
        build_all.latex(STEM)
    text = log.read_text(errors="replace")
    if (still := too_wide(text)):
        print(f"warning: wider than even a landscape page: {', '.join(sorted(still))}")
    if (tall := sum(1 for l in text.splitlines() if l.startswith("Overfull \\vbox"))):
        print(f"warning: {tall} page(s) with content taller than the page (a table that does not fit one page)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
