"""Generate the analysis reports in results/reports/ from result files (Phases 10, 12, 13).

Interpretive labels are produced by fixed, pre-declared rules (not by hand):
    ranking inverted            AUC < 0.45
    near chance                 0.45 <= AUC <= 0.55
    ranking transfers but       AUC >= 0.85 and accuracy at the validation threshold < 0.70
      threshold does not
    transfers                   AUC >= 0.85 and accuracy >= 0.70
    partial                     otherwise
Every value is tagged with its status; a report that uses any placeholder starts with a warning.

Usage:
    python .scripts/generate_reports.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
REP = ROOT / "results" / "reports"
REP.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(ROOT / "src"))
from bscan.registry import load_registry, resolve, status_table  # noqa: E402

REG = load_registry()
LABEL = {k: v["label"] for k, v in REG["models"].items()}
CORP = {("P1", "internal_test"): "BF-SUST (internal)", ("P1", "external_BF-MOZ"): "BF-MOZ", ("P1", "external_MEN"): "MEN",
        ("P2", "internal_test"): "MEN (internal)", ("P2", "external_BF-SUST"): "BF-SUST", ("P2", "external_BF-MOZ"): "BF-MOZ"}
WARN = ("> **WARNING — this report contains SYNTHETIC PLACEHOLDER values (marked †). They are not results.**\n"
        "> Run the Colab notebooks, copy the returned runs into `results/runs/`, then run `python .scripts/build_all.py`.\n\n")


def v(x, st="real", kind="auc"):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "—"
    s = f"{100 * x:.1f}%" if kind == "pct" else (f"{x:.2e}" if kind == "p" and x < 1e-3 else f"{x:.3f}")
    return s + ("†" if st != "real" else "")


def rule(auc, acc):
    if auc != auc:
        return "—"
    if auc < 0.45:
        return "ranking inverted"
    if auc <= 0.55:
        return "near chance"
    if auc >= 0.85 and acc == acc and acc < 0.70:
        return "ranking transfers, threshold does not"
    if auc >= 0.85:
        return "transfers"
    return "partial"


def header(title: str, uses_ph: bool, sources: list[str]) -> str:
    h = f"# {title}\n\n*Generated by `.scripts/generate_reports.py` from: {', '.join(f'`{s}`' for s in sources)}. Do not edit by hand.*\n\n"
    return h + (WARN if uses_ph else "")


def report_cross() -> None:
    s = pd.read_csv(ROOT / "results/stats/multiseed_summary.csv")
    rows, uses_ph = [], False
    for model in ["bscan_controlled", "mel_only", "lfcc_only", "lcnn_lfcc", "lfcc_gmm_controlled", "stats_hgb_controlled",
                  "bscan_orig6s", "stats_hgb_orig6s"]:
        for proto in ("P1", "P2"):
            sub = s[(s.model == model) & (s.protocol == proto)]
            for _, r in sub.iterrows():
                uses_ph |= r.status == "placeholder"
                rows.append(f"| {LABEL[model]} | {'BF-SUST' if proto == 'P1' else 'MEN'} | {CORP[(proto, r.split)]} | "
                            f"{v(r.auc_mean, r.status)} | {v(r.eer_mean, r.status, 'pct')} | {v(r.accuracy_mean, r.status, 'pct')} | "
                            f"{v(r.recall_spoof_sensitivity_mean, r.status, 'pct')} | {v(r.specificity_bonafide_recall_mean, r.status, 'pct')} | "
                            f"{rule(r.auc_mean, r.accuracy_mean) if 'internal' not in CORP[(proto, r.split)] else 'in-corpus'} |")
    eg = ROOT / "results/analysis/error_groups.csv"
    err = ""
    if eg.exists():
        g = pd.read_csv(eg)
        g = g[(g.run == "bscan_controlled__P1__seed42") & (g.split == "external_MEN")]
        if len(g):
            uses_ph |= (g.status != "real").any()
            err = "\n## Error structure of BSCAN on MEN (P1, seed 42)\n\n| Grouping | Level | n spoof | FNR | n bona fide | FPR |\n|---|---|---:|---:|---:|---:|\n"
            for _, r in g[g.grouping.isin(["gender", "duration_tertile", "snr_proxy_tertile", "trailing_silence", "clipping"])].iterrows():
                err += f"| {r.grouping} | {r.level} | {r.n_spoof} | {v(r.fnr, r.status, 'pct')} | {r.n_bonafide} | {v(r.fpr, r.status, 'pct')} |\n"
    txt = header("06 — Cross-Dataset Analysis (Phase 10)", uses_ph,
                 ["results/stats/multiseed_summary.csv", "results/analysis/error_groups.csv"])
    txt += ("Rows: model, training corpus, test corpus. Metrics are recording-level; accuracy, sensitivity and "
            "specificity use the validation-derived threshold of each run (never tuned on test data). Values are the "
            "mean over the seeds run. Transfer labels follow the fixed rules in the script header.\n\n"
            "| Model | Trained on | Tested on | AUC | EER | Accuracy | Sensitivity (spoof) | Specificity (bona fide) | Transfer |\n"
            "|---|---|---|---:|---:|---:|---:|---:|---|\n" + "\n".join(rows) + "\n" + err)
    txt += ("\n## Reading guide\n\n* **ranking inverted**: the detector systematically scores bona fide recordings of the target corpus as more "
            "spoof-like than its spoofs — the signature of corpus-specific cues whose direction flips across corpora "
            "(see the dataset shortcut audit, Sec. III-C of the paper).\n* **ranking transfers, threshold does not**: scores still separate the "
            "classes (high AUC) but the validation threshold no longer sits between them — a calibration shift.\n")
    (REP / "cross_dataset_analysis.md").write_text(txt)


def _analysis(kind: str) -> tuple[pd.DataFrame, bool]:
    frames, ph = [], False
    for rn in REG["analyses"][kind]["runs"]:
        real = ROOT / "results/runs" / rn / f"{kind}_summary.csv"
        plc = ROOT / "results/runs_PLACEHOLDER" / rn / f"{kind}_summary.csv"
        if real.exists():
            f, st = pd.read_csv(real), "real"
        elif plc.exists():
            f, st, ph = pd.read_csv(plc), "placeholder", True
        else:
            continue
        f["run"], f["status"] = rn, st
        frames.append(f)
    return (pd.concat(frames) if frames else pd.DataFrame()), ph


def report_robustness() -> None:
    rb, ph1 = _analysis("robustness")
    pr, ph2 = _analysis("probes")
    txt = header("07 — Robustness and Counterfactual Probe Analysis (Phase 12)", ph1 or ph2,
                 ["results/runs/*/robustness_summary.csv", "results/runs/*/probes_summary.csv"])
    txt += ("All perturbations are applied at test time to the 16 kHz recording before each model's own preprocessing; "
            "no model is retrained. Up to 600 recordings per test set (stratified, identical for every model and "
            "condition). ΔAUC is relative to the clean condition of the same model and test set.\n\n")
    if not rb.empty:
        txt += "## Robustness (recording-level AUC and ΔAUC vs clean)\n\n| Model | Condition | " + " | ".join(
            CORP[("P1", s)] for s in REG["analyses"]["robustness"]["splits"]) + " |\n|---|---|" + "---:|" * len(
            REG["analyses"]["robustness"]["splits"]) + "\n"
        for (rn, cond), g in rb.groupby(["run", "condition"], sort=False):
            cells = []
            for sp in REG["analyses"]["robustness"]["splits"]:
                a = g[g.split == sp]
                c0 = rb[(rb.run == rn) & (rb.split == sp) & (rb.condition == "clean")]
                if len(a) and len(c0):
                    cells.append(f"{v(float(a.auc.iloc[0]), a.status.iloc[0])} (Δ {float(a.auc.iloc[0]) - float(c0.auc.iloc[0]):+.3f})")
                else:
                    cells.append("—")
            txt += f"| {LABEL[rn.split('__')[0]]} | {cond} | " + " | ".join(cells) + " |\n"
    if not pr.empty:
        txt += ("\n## Counterfactual shortcut probes\n\nEach probe adds or removes exactly one cue found in Phase 3. "
                "A large decision-flip rate means the model's decisions depend on that cue.\n\n"
                "| Model | Probe | Test set | Δscore bona fide | Δscore spoof | Decisions flipped |\n|---|---|---|---:|---:|---:|\n")
        for _, r in pr[pr.condition != "clean"].iterrows():
            txt += (f"| {LABEL[r.run.split('__')[0]]} | {r.condition} | {CORP[('P1', r.split)]} | "
                    f"{v(r.mean_score_shift_bonafide, r.status)} | {v(r.mean_score_shift_spoof, r.status)} | "
                    f"{v(r.decision_flip_rate, r.status, 'pct')} |\n")
    (REP / "robustness_analysis.md").write_text(txt)


def report_stats() -> None:
    s = pd.read_csv(ROOT / "results/stats/multiseed_summary.csv")
    p = pd.read_csv(ROOT / "results/stats/paired_comparisons.csv")
    cal = ROOT / "results/analysis/calibration.csv"
    uses_ph = bool((s.status != "real").any() or (len(p) and (p.status != "real").any()))
    txt = header("08 — Statistical Analysis (Phase 13)", uses_ph,
                 ["results/stats/multiseed_summary.csv", "results/stats/paired_comparisons.csv", "results/analysis/calibration.csv"])
    st_tab = pd.DataFrame(status_table())
    txt += ("## Run completeness\n\n" + st_tab.groupby(["stage", "status"]).size().rename("runs").reset_index().to_markdown(index=False) + "\n\n")
    txt += ("## Variability across training seeds (42, 123, 2026)\n\nMean ± SD of recording-level AUC over the seeds run "
            "(n shown). Seeds were fixed before any repeated-seed result was seen.\n\n| Model | Protocol | Test set | n seeds | AUC mean ± SD | EER mean ± SD |\n|---|---|---|---:|---:|---:|\n")
    for _, r in s[s.auc_n > 1].iterrows():
        txt += (f"| {LABEL[r.model]} | {r.protocol} | {CORP[(r.protocol, r.split)]} | {int(r.auc_n)} | "
                f"{v(r.auc_mean, r.status)} ± {v(r.auc_sd, r.status)} | {v(r.eer_mean, r.status, 'pct')} ± {v(r.eer_sd, r.status, 'pct')} |\n")
    if len(p) and "delta_auc" in p:
        txt += ("\n## Paired comparisons (seed 42, same recordings)\n\nDeLong test for correlated AUCs (Holm-adjusted within "
                "each protocol × test set), 95% CI of ΔAUC by cluster bootstrap over sentence groups (BanglaFake) or "
                "speakers (MEN), exact McNemar test on decisions at each model's own validation threshold.\n\n"
                "| A | B | Protocol | Test set | ΔAUC (A−B) [95% CI] | DeLong p (Holm) | McNemar p |\n|---|---|---|---|---:|---:|---:|\n")
        for _, r in p[p.delta_auc.notna()].iterrows():
            txt += (f"| {LABEL[r.run_a.split('__')[0]]} | {LABEL[r.run_b.split('__')[0]]} | {r.protocol} | "
                    f"{CORP[(r.protocol, r.split)]} | {v(r.delta_auc, r.status)} [{v(r.delta_auc_ci_low, r.status)}, "
                    f"{v(r.delta_auc_ci_high, r.status)}] | {v(r.delong_p_holm, r.status, 'p')} | {v(r.mcnemar_p, r.status, 'p')} |\n")
    if cal.exists():
        c = pd.read_csv(cal)
        if len(c):
            uses_ph |= (c.status != "real").any()
            txt += "\n## Calibration (probabilities = sigmoid of the recording score)\n\n| Run | Test set | ECE | Brier |\n|---|---|---:|---:|\n"
            for _, r in c.iterrows():
                txt += f"| {r.run} | {CORP[('P1', r.split)]} | {v(r.ece, r.status)} | {v(r.brier, r.status)} |\n"
    txt += ("\n## Methods notes\n\n* Why these tests: DeLong compares two correlated ROC AUCs on the same recordings; McNemar "
            "compares paired binary decisions. Neither assumes normality of the metric across recordings.\n* Pseudo-replication: "
            "confidence intervals resample independent units (sentence groups or speakers), not windows or duplicated files.\n"
            "* Multiple comparisons: Holm correction within each protocol × test set family.\n")
    (REP / "statistical_analysis.md").write_text(txt)


def main() -> None:
    report_cross()
    report_robustness()
    report_stats()
    print(f"reports written to {REP.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
